# Generated by Django 4.1.1 on 2022-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(default='Bronze', editable=False, max_length=150),
        ),
    ]
