# Generated by Django 4.1.1 on 2022-09-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='category',
        ),
    ]
