# Generated by Django 4.1.1 on 2022-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
